@server = http://localhost:8080
@movieId = 2

### Get all movies
GET {{server}}/movies


### Get a movie by id
GET {{server}}/movies/{{movieId}}

### create a movie
POST {{server}}/movies

{
    "title": "Shrek",
    "director": "Nolan"
}

### update a movie
PUT {{server}}/movies/{{movieId}}

{
    "title": "The Dark Knight",
    "director": "Christopher Nolan"
}

### delete a movie
DELETE {{server}}/movies/{{movieId}}

### search movies by title
GET {{server}}/movies/search?title=tion


### search Movie by director name
GET {{server}}/movies/search

### only title
GET {{server}}/movies/search?title=Inception


### only directory
GET {{server}}/movies/search?director=Christopher1

###
GET {{server}}/movies/search?director=Nolan&title=Inception
